menu:
    Blog: /
    GitHub: https://github.com/libAudioFlux/audioFlux
    Doc: https://audioflux.top
    Archive: archives/
    Feed: atom.xml

favicon: icon.png
logo: logo.png

# Comment
# e.g disqus: claymcleod 
disqus: 

# Analytics
ga: G-DG0JNF2WF8

# Copyright Infomation
startyear: 2022

# Image Credits
enable_image_credit: false 
